package other;

import junit.framework.Assert;
import org.junit.jupiter.api.Test;

public class SkuTest {

    @Test
    public void testStringTheSameAfterRemoveEndecaTag() {
        String skuCorrect = "<sku><productId>00085369992051</productId><onSale/><id>00085369992051</id><productDescription>PROTECTOR TOUGH ARMOR IPHONE 7 ORO</productDescription><productDisplayName>Funda Protectora para iPhone 7</productDisplayName><productSeoUrl>/celulares/fundas-micas-y-accesorios/protectores-micas-y-soportes/funda-protectora-para-iphone-7-spigen-tough-armor-dorado_00085369992051</productSeoUrl><productDisplayText>Funda Protectora para iPhone 7 Spigen Tough Armor Dorado</productDisplayText><productDepartment><item>Celulares</item></productDepartment><productFamily><item>Fundas Micas y Accesorios</item></productFamily><productFineline><item>Protectores Micas y Soportes</item></productFineline><departmentUrl><item>celulares</item></departmentUrl><familyUrl><item>fundas-micas-y-accesorios</item></familyUrl><finelineUrl><item>protectores-micas-y-soportes</item></finelineUrl><productShopTicketDesc>Tough Armor Dorado</productShopTicketDesc><productRatings/><productDateAvailable>1537566808444</productDateAvailable><productDaysAvailable>383</productDaysAvailable><topSelling>true</topSelling><skuDisplayName>Funda Protectora para iPhone 7 Spigen Tough Armor Dorado</skuDisplayName><skuDescription>PROTECTOR TOUGH ARMOR IPHONE 7 ORO</skuDescription><unitOfMeasure/><largeImageUrl>/gm/1p/images/product-images/img_large/00085369992051l.jpg</largeImageUrl><smallImageUrl>/gm/1p/images/product-images/img_small/00085369992051s.jpg</smallImageUrl><freeShippingItem>No Free Shipping</freeShippingItem><skuPrice>0.0</skuPrice><bigItem>false</bigItem><onDemand>false</onDemand><preOrderable>false</preOrderable><pickUpEnabled>true</pickUpEnabled><bundle>false</bundle><salesRank/><brandName>spigen</brandName><specialEventName/><specialEventImage/><seoKeywords/><skuAttributes><facet_7>ancho (cm)_facet_17</facet_7><facet_8>fondo (cm)_facet_1</facet_8><facet_3>contenido del empaque_facet_1 funda protectora y 1 manual de usuario</facet_3><facet_5>alto (cm)_facet_9</facet_5><facet_6>gama_color_facet_dorado</facet_6><facet_9>modelo_facet_sgip7ta042cs20490</facet_9><facet_1>peso (kg)_facet_0.1</facet_1><facet_4>color_facet_dorado</facet_4><facet_2>garantía_facet_directo con el proveedor</facet_2></skuAttributes></sku>";
        String skuAfterRemoved = "<sku><productId>00085369992051</productId><onSale/><id>00085369992051</id><productDescription>PROTECTOR TOUGH ARMOR IPHONE 7 ORO</productDescription><productDisplayName>Funda Protectora para iPhone 7</productDisplayName><productSeoUrl>/celulares/fundas-micas-y-accesorios/protectores-micas-y-soportes/funda-protectora-para-iphone-7-spigen-tough-armor-dorado_00085369992051</productSeoUrl><productDisplayText>Funda Protectora para iPhone 7 Spigen Tough Armor Dorado</productDisplayText><productDepartment><item>Celulares</item></productDepartment><productFamily><item>Fundas Micas y Accesorios</item></productFamily><productFineline><item>Protectores Micas y Soportes</item></productFineline><departmentUrl><item>celulares</item></departmentUrl><familyUrl><item>fundas-micas-y-accesorios</item></familyUrl><finelineUrl><item>protectores-micas-y-soportes</item></finelineUrl><productShopTicketDesc>Tough Armor Dorado</productShopTicketDesc><productRatings/><productDateAvailable>1537566808444</productDateAvailable><productDaysAvailable>383</productDaysAvailable><topSelling>true</topSelling><skuDisplayName>Funda Protectora para iPhone 7 Spigen Tough Armor Dorado</skuDisplayName><skuDescription>PROTECTOR TOUGH ARMOR IPHONE 7 ORO</skuDescription><unitOfMeasure/><largeImageUrl>/gm/1p/images/product-images/img_large/00085369992051l.jpg</largeImageUrl><smallImageUrl>/gm/1p/images/product-images/img_small/00085369992051s.jpg</smallImageUrl><freeShippingItem>No Free Shipping</freeShippingItem><skuPrice>0.0</skuPrice><bigItem>false</bigItem><onDemand>false</onDemand><preOrderable>false</preOrderable><pickUpEnabled>true</pickUpEnabled><bundle>false</bundle><salesRank/><brandName>spigen</brandName><specialEventName/><specialEventImage/><seoKeywords/><skuAttributes><facet_7>ancho (cm)_facet_17</facet_7><facet_8>fondo (cm)_facet_1</facet_8><facet_3>contenido del empaque_facet_1 funda protectora y 1 manual de usuario</facet_3><facet_5>alto (cm)_facet_9</facet_5><facet_6>gama_color_facet_dorado</facet_6><facet_9>modelo_facet_sgip7ta042cs20490</facet_9><facet_1>peso (kg)_facet_0.1</facet_1><facet_4>color_facet_dorado</facet_4><facet_2>garantía_facet_directo con el proveedor</facet_2></skuAttributes></sku>";
        Assert.assertEquals(skuCorrect, skuAfterRemoved);
    }
}
